services:
  - type: web
    name: communityfix-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production